import type { Metadata } from "next";
import { Geist, Geist_Mono, Raleway } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from '@clerk/nextjs';

// Configure Raleway
const raleway = Raleway({
  subsets: ["latin"],
  display: 'swap', // Use swap for better performance
  variable: '--font-raleway', // Define CSS variable name
  
  weight: ['400', '700', '900']
});

export const metadata: Metadata = {
  title: "RoastMe.ai - Get Roasted by AI!",
  description: "Upload your bio or picture and get a hilarious roast generated by AI.",
};
  
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={`${raleway.className}  bg-slate-900 text-white`}>
      
        {children}
      </body>
    </html></ClerkProvider>
  );
}
